---
title: "Lab3"
author: "Joao Vitor Ogata Kodama"
date: "22 de janeiro de 2016"
output: html_document
---

```{r}
#Pacotes
install.packages("nycflights13")
library(nycflights13)
library(dplyr)
library(tidyr)
```

```{r}
#Filter
#1
flights %>% 
  filter(month==1, year==2013)
#2
flights %>% 
  filter(month<=2, year==2013)
#3
flights %>% 
  filter(distance>1000)
```

```{r}
#Select
#1
flights %>% 
  select(month, dep_delay)
#2
flights %>% 
  select(mes = month, atraso = dep_delay)
#3
flights %>% 
  select(-tailnum, -origin, -dest)
```

```{r}
#Mutate
#1
flights %>% 
  mutate(ganho_de_tempo = dep_delay - arr_delay, velocidade = distance / air_time * 60) %>% 
  select(flight, dep_time, arr_time, ganho_de_tempo, velocidade)
#2
flights %>% 
  mutate(minutos_totais = hour * 60 + minute + air_time, hour2 = minutos_totais %/% 60, minute2 = minutos_totais %% 60) %>% 
  select(flight, origin, dest, hour, minute, air_time, hour2, minute2)
```

```{r}
#Summarise
#1
flights %>% 
  summarise(mean(distance))
#2
por_mes <- flights %>% group_by(month)
por_mes %>% summarise(mean(distance))
#3
por_mes <- flights %>% group_by(month)
por_mes %>% summarise(mediana = median(distance), quartil1 = quantile(distance, probs = c(0.25), na.rm = FALSE), media = mean(distance), quartil3 = quantile(distance, probs = c(0.75), na.rm = FALSE))
```

```{r}
#Arrange
#1
flights %>% 
  select(flight, year, month, carrier, origin, dest, dep_delay) %>% 
  arrange(dep_delay)
#2
flights %>% 
  select(flight, year, month, carrier, origin, dest, dep_delay) %>% 
  arrange(desc(dep_delay))
```

```{r}
#Spread
#1
flights %>%
  group_by(month, day) %>%
  summarise(atraso_medio = mean(dep_delay, na.rm = T)) %>%
  spread(month, atraso_medio)
#2
flights %>%
  group_by(day, hour) %>%
  summarise(atraso_medio = mean(dep_delay, na.rm = T)) %>%
  spread(day, atraso_medio)
```

```{r}
#Gather
#1
flights %>%
  group_by(month, day) %>%
  summarise(atraso_medio = mean(dep_delay, na.rm = T)) %>%
  spread(month, atraso_medio) %>% 
  gather(month, atraso_medio, -day) %>% 
  filter(atraso_medio != "")
#2
flights %>%
  group_by(day, hour) %>%
  summarise(atraso_medio = mean(dep_delay, na.rm = T)) %>%
  spread(day, atraso_medio) %>% 
  gather(day, atraso_medio, -hour) %>% 
  filter(atraso_medio != "")
```
