---
title: "lab4"
author: "Joao Vitor Ogata Kodama"
date: "January 28, 2016"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(lubridate)
```

####geom_point
```{r}
#1 
#aes: x, y, alpha, colour, fill, shape, size and stroke
#aes obrigatórios: x e y

#2
sample_n(diamonds, 5000) %>% 
  ggplot() +
  geom_point(alpha = 0.2, aes(x = price, y = carat)) +
  labs(x = "Preço (US$)", y = "Peso (Quilates)")
  
#3
sample_n(diamonds, 5000) %>% 
  ggplot() +
  geom_point(alpha = 0.2, aes(x = price, y = carat)) +
  facet_wrap(~clarity) +
  labs(x = "Preço (US$)", y = "Peso (Quilates)")
```

####geom_histogram
```{r}
#4
#aes: x, alpha, colour, fill, linetype and size
#aes obrigatórios: x

#5
diamonds %>% 
  ggplot(aes(x = price)) +
  geom_histogram(colour = "white", fill = "darkslateblue")

#6
diamonds %>% 
  ggplot(aes(price, fill = price)) +
  geom_histogram(aes(y = ..density..),colour = "white", fill = "darkslateblue") +
  geom_density()
```

####geom_boxplot
```{r}
#7
#aes: lower, middle, upper, x, ymax, ymin, alpha, colour, fill, linetype, shape, size and weight
#aes obrigatórios: lower, middle, upper, x, ymax and ymin

#8
diamonds %>% 
  ggplot(aes(cut, price)) +
  geom_boxplot(aes(colour = cut))

#9
diamonds %>% 
  ggplot(aes(cut, price)) +
  geom_boxplot(aes(colour = cut)) +
  labs(colour = "") +
  scale_colour_manual(values = c("yellow", "orange", "orange4", "tomato", "red"))
```

####geom_bar
```{r}
#10
#aes: x, alpha, colour, fill, linetype, size
#aes obrigatórios: x

#11
diamonds %>% 
  ggplot(aes(x = color, fill = color)) +
  geom_bar()
```

####economics
```{r}
#12
economics %>% 
  ggplot(aes(x = unemploy, y = uempmed)) +
  geom_point(alpha = 0.35)

#13
library(lubridate)
economics %>% 
  mutate(date_ano = year(date)) %>% 
  ggplot(aes(x = unemploy, y = uempmed, colour = date_ano)) +
  geom_point(alpha = 0.50) +
  labs(colour = "Ano")

#14
economics %>% 
  ggplot(aes(y = unemploy, x = date)) +
  geom_line(size = 0.5)

#15
economics %>% 
  mutate(date_ano = year(date)) %>% 
  group_by(date_ano) %>% 
  summarise(unemploy_med = mean(unemploy, na.rm = T)) %>% 
  ggplot(aes(y = unemploy_med, x = date_ano)) +
  geom_line(size = 0.5) +
  labs(x = "Data (ano)", y = "Desempregados (média anual)")

#16
economics %>% 
  mutate(date_ano = year(date)) %>% 
  group_by(date_ano) %>% 
  summarise(unemploy_median = median(unemploy, na.rm = T),
            unemploy_1quart = quantile(unemploy, 0.01, na.rm = T),
            unemploy_3quart = quantile(unemploy, 0.99, na.rm = T)) %>%
  ggplot(aes(x = date_ano, y = unemploy_median)) +
  geom_line()+
  geom_ribbon(aes(ymin = unemploy_1quart, ymax = unemploy_3quart), alpha = 0.2)


#17
economics %>% 
  mutate(taxa_desemprego = unemploy/pop, date_ano = year(date)) %>% 
  group_by(date_ano) %>% 
  summarise("pce_med" = mean(pce, na.rm = T), "psavert_med" = mean(psavert, na.rm = T), "taxa_med" = mean(taxa_desemprego, na.rm = T)) %>% 
  gather(pce_med, valor, -date_ano) %>% 
  ggplot(aes(x = date_ano, y = valor)) +
  geom_line(size = 1) +
  facet_wrap(~pce_med, scales = "free_y", dir = "v")
```
