---
title: "lab5"
author: "Curso R de verão 2016"
date: "29 de janeiro de 2016"
output: html_document
---
```{r}
library(ggplot2)
library(magrittr)
library(tidyr)
library(dplyr)
install.packages("jpeg")
library(jpeg)
install.packages("tree")
library(tree)
```

```{r}
# a) carrega uma imagem jpeg no R 
img <- readJPEG("purple_wave.jpg")

# b) transforma o array da imagem em data.frame com infos de posicao (x,y) e cor (r,g,b)
# dimensões da imagem
img_dim <- dim(img)

# RGB para data.frame
img_df <- data.frame(
  x = rep(1:img_dim[2], each = img_dim[1]),
  y = rep(img_dim[1]:1, img_dim[2]),
  r = as.vector(img[,,1]),
  g = as.vector(img[,,2]),
  b = as.vector(img[,,3])
) %>%
  mutate(cor = rgb(r, g, b),
         id = 1:n())

View(img_df)
```

```{r}
# para reprodução
set.seed(1) 

# Parte 1) x, y, r, g
img_df_parte1 <- img_df %>% 
  sample_frac(3/5) %>% # separando 3/5 do banco
  mutate(b_backup = b, # backup do azul original
         b = 0, # retirando o azul da imagem
         cor = rgb(r, g, b)) # cor da imagem sem o azul

# Parte 2) x, y, r, g, b
img_df_parte2 <- img_df %>% filter(!id%in%img_df_parte1$id) # filtra as linhas que estão na Parte 1
```

```{r}
#Wave original
wave_original <- ggplot(data = img_df, aes(x = x, y = y)) + 
  geom_point(colour = img_df$cor) +
  labs(x = "x", y = "y", title = "Original") +
  coord_fixed(ratio = 1) +
  theme_bw()
wave_original
```

```{r}
# Imagem sem o azul
wave_semazul <- ggplot(data = img_df_parte1, aes(x = x, y = y)) + 
  geom_point(colour = img_df_parte1$cor) +
  labs(x = "x", y = "y", title = "Imagem sem azul") +
  coord_fixed(ratio = 1) +
  theme_bw()
wave_semazul
```

```{r}
# Com o azul da imagem
ggplot(data = img_df_parte2, aes(x = x, y = y)) + 
  geom_point(colour = img_df_parte2$cor) +
  labs(x = "x", y = "y", title = "Imagem com B (azul)") +
  coord_fixed(ratio = 1) +
  theme_bw()
```

```{r}
#1
img_df_amostra <- img_df %>% 
  sample_n(500,replace = FALSE)

cor(img_df_amostra %>% 
      select(-cor, -id)) %>% 
  round(2)

pairs(img_df_amostra %>%
  select(-cor, -id))
```

```{r}
#2
modelo_lm <- lm(b ~ r, data = img_df_parte2)
summary(modelo_lm)

predito_lm <- predict(modelo_lm, img_df_parte1)
img_df_parte1$new.col <- predito_lm #é preciso criar um novo "cor"
img_df_parte1$new.cor <- rgb(img_df_parte1$r, img_df_parte1$g, abs(img_df_parte1$new.col)) #transformando os números em positivos
wave_predito_lm <- ggplot(data = img_df_parte1, aes(x = x, y = y)) + 
  geom_point(colour = img_df_parte1$new.cor) +
  labs(x = "x", y = "y", title = "Previsão LM") +
  coord_fixed(ratio = 1) +
  theme_bw()
wave_predito_lm
```

```{r}
#3
modelo_tree <- tree(b ~ r, data = img_df_parte2)
summary(modelo_tree)

predito_tree <- predict(modelo_tree, img_df_parte1)
img_df_parte1$new.col <- predito_tree #é preciso criar um novo "cor"
img_df_parte1$new.cor <- rgb(img_df_parte1$r, img_df_parte1$g, abs(img_df_parte1$new.col)) #transformando os números em positivos
wave_predito_tree <- ggplot(data = img_df_parte1, aes(x = x, y = y)) + 
  geom_point(colour = img_df_parte1$new.cor) +
  labs(x = "x", y = "y", title = "Previsão Tree") +
  coord_fixed(ratio = 1) +
  theme_bw()
wave_predito_tree
```

```{r}
#5
img2 <- readJPEG("xadrez_colorido.jpg")

img_dim2 <- dim(img2)

img_df2 <- data.frame(
  x = rep(1:img_dim2[2], each = img_dim2[1]),
  y = rep(img_dim2[1]:1, img_dim2[2]),
  r = as.vector(img2[,,1]),
  g = as.vector(img2[,,2]),
  b = as.vector(img2[,,3])
) %>%
  mutate(cor = rgb(r, g, b),
         id = 1:n())

View(img_df2)

set.seed(1)

img_df_parte1a <- img_df2 %>% 
  sample_frac(3/5) %>% # separando 3/5 do banco
  mutate(b_backup = b, # backup do azul original
         b = 0, # retirando o azul da imagem
         cor = rgb(r, g, b)) # cor da imagem sem o azul

img_df_parte2a <- img_df2 %>% filter(!id%in%img_df_parte1a$id)

#Imagem original
xadrez_original <- ggplot(data = img_df2, aes(x = x, y = y)) + 
  geom_point(colour = img_df2$cor) +
  labs(x = "x", y = "y", title = "Original") +
  coord_fixed(ratio = 1) +
  theme_bw()
xadrez_original

#Imagem com o azul no xadrez
ggplot(data = img_df_parte2a, aes(x = x, y = y)) + 
  geom_point(colour = img_df_parte2a$cor) +
  labs(x = "x", y = "y", title = "Imagem com B (azul)") +
  coord_fixed(ratio = 1) +
  theme_bw()
#Imagem sem o azul no xadrez
ggplot(data = img_df_parte1a, aes(x = x, y = y)) + 
  geom_point(colour = img_df_parte1a$cor) +
  labs(x = "x", y = "y", title = "Imagem sem B (azul)") +
  coord_fixed(ratio = 1) +
  theme_bw()

#Análise
img_df_amostra2 <- img_df2 %>% 
  sample_n(500,replace = FALSE)

cor(img_df_amostra2 %>% 
      select(-cor, -id)) %>% 
  round(2)

pairs(img_df_amostra2 %>%
  select(-cor, -id))

modelo_lm2 <- lm(b ~ x + r + g , data = img_df_parte2a)


predito_lm2 <- predict(modelo_lm2, img_df_parte1a)
img_df_parte1a$new.col <- predito_lm2 #é preciso criar um novo "cor"
img_df_parte1a$new.cor <- rgb(img_df_parte1a$r, img_df_parte1a$g, abs(img_df_parte1a$new.col)) #transformando os números em positivos
xadrez_predito_lm <- ggplot(data = img_df_parte1a, aes(x = x, y = y)) + 
  geom_point(colour = img_df_parte1a$new.cor) +
  labs(x = "x", y = "y", title = "Previsão LM") +
  coord_fixed(ratio = 1) +
  theme_bw()
xadrez_predito_lm

modelo_tree2 <- tree(b ~ x, data = img_df_parte2a)
summary(modelo_tree2)

predito_tree2 <- predict(modelo_tree2, img_df_parte1a)
img_df_parte1a$new.col <- predito_tree2 #é preciso criar um novo "cor"
img_df_parte1a$new.cor <- rgb(img_df_parte1a$r, img_df_parte1a$g, abs(img_df_parte1a$new.col)) #transformando os números em positivos
xadrez_predito_tree <- ggplot(data = img_df_parte1a, aes(x = x, y = y)) + 
  geom_point(colour = img_df_parte1a$new.cor) +
  labs(x = "x", y = "y", title = "Previsão Tree") +
  coord_fixed(ratio = 1) +
  theme_bw()
xadrez_predito_tree
```

```{r}
#Gráficos lado a lado para comparar
install.packages("gridExtra")
library(gridExtra)
install.packages("cowplot")
library(cowplot)

#WAVE
plot_grid(wave_original, wave_predito_lm, wave_predito_tree, ncol = 1, nrow = 3)

#XADREZ
plot_grid(xadrez_original, xadrez_predito_lm, xadrez_predito_tree, ncol = 1, nrow = 3)
```
